@startuml
class EasterEggState {
    + <<override>> Enter(manager:GameManager) : void
    + <<override>> Execute() : void
    + <<override>> Exit() : void
    + <<override>> GetNextState() : Type
}
AbstractMSM <|-- EasterEggState
@enduml
