@startuml
class ErrorState {
    + ErrorState(manager:GameManager)
    + <<override>> Enter() : void
    + <<override>> Execute() : void
    + <<override>> Exit() : void
    + <<override>> GetNextState() : Type
}
AbstractMSM <|-- ErrorState
@enduml
