@startuml
class UploadGameState {
    + UploadGameState(manager:GameManager)
    + <<override>> Enter() : void
    + <<override>> Execute() : void
    + <<override>> Exit() : void
    + <<override>> GetNextState() : Type
}
AbstractMSM <|-- UploadGameState
@enduml
