@startuml
'https://plantuml.com/state-diagram

scale 350 width
hide empty description
skinparam backgroundColor transparent

[*] -> StartState
state StartState{
StartState: Exit: Switch to AR

    [*] -> SplashScreen
    SplashScreen -> [*]
}
StartState -> EasterEgg1: UserConfirm

EasterEgg1: Entry:  Spawn Object
EasterEgg1: Do:     Check Raycast
EasterEgg1: Exit:   Destroy Object
EasterEgg1 -> UploadGame: EggTouched

state UploadGame {
    UploadGame: Entry:  ShowUI
    UploadGame: Do:     SubState
    UploadGame: Exit:   HideUI

    [*] -> UploadUI
    UploadUI -> [*]
}
UploadGame -> EasterEgg2

EasterEgg2: Entry:  Spawn Object
EasterEgg2: Do:     Check Raycast
EasterEgg2: Exit:   Destroy Object
EasterEgg2 --> ChargeGame: EggTouched

state ChargeGame {
    ChargeGame: Entry:  <NA>
    ChargeGame: Do:     SubState
    ChargeGame: Exit:   Destroy Object

    [*] -> SpawnModel1
    SpawnModel1 -down-> ChargerFlow
    ChargerFlow -left-> [*]
}
ChargeGame -left> EasterEgg3

EasterEgg3: Entry:  Spawn Object
EasterEgg3: Do:     Check Raycast
EasterEgg3: Exit:   Destroy Object
EasterEgg3 -left> PrintGame: EggTouched

state PrintGame {
    PrintGame: Entry:  <NA>
    PrintGame: Do:     SubState
    PrintGame: Exit:   Destroy Object

    [*] -> SpawnModel2
    SpawnModel2 -down-> PrinterFlow
    PrinterFlow -left-> [*]
}
PrintGame -left> [*]

@enduml