@startuml
class ARSpawnManager {
    + canPlace : bool <<get>>
    + SpawnEgg() : void
    + DestroyEgg() : void
    + Update3DTracking() : void
}
MonoBehaviour <|-- ARSpawnManager
ARSpawnManager --> "printerPrefab" GameObject
ARSpawnManager --> "eggPrefab" GameObject
ARSpawnManager --> "eggInstance" GameObject
@enduml
